### ISSUE TITLE
Recording To Disk Breaks Companion Feedback

### ISSUE THREAD

**Issue by Brotuulaan** [bitfocus/companion-module-obs-studio#154] opened 2022-07-19 15:58 UTC
OBS 27.2.4, Windows 10 (21H2)

I set up buttons for transitions (both generic preview/program and specific scenes) and added feedback options for colors to indicate the live scene, but then when we used it Sunday, the feedback stopped working. It took a bit of time to track down, but I eventually found that when OBS starts recording, that breaks the feedback. Controls still work, but colors don't update. That led to mistaken scene switching and our audio being run over by our pre-service music for a fair chunk of the first song.

We have record set to auto-start with the stream, so I originally thought it was streaming that started it, but streaming on its own doesn't do it.

Right now, the only fix that I've found is to restart the Companion server. That's not usually an option when live since it's running on a computer that's used to run lyrics and such, so we'll just have to live with it until it's fixed.

**Comment by myntath** [comment] 2022-07-24 02:38
I can confirm I have a similar issue. Also OBS 27.2.4 Companion 2.2.3.

Recording is set to use Stream Encoding in OBS although I tried a few other settings and still had issues (including mkv/mp4 and using a separate encoder).

I first noticed this because we previously had feedback for a toggle recording button which stopped working, which was odd for a seemingly simple button. So I think there was a regression at some point.

**Comment by bryce-seifert** [comment] 2022-07-24 16:32
Did this issue occur prior to 2.2.3 or is that unknown?

If you turn off all modules besides OBS does it still happen?

As a note, I'm very close to being done with the 5.0 rewrite for the new version of obs-websocket. So that will likely be the fix once that's ready, unless I can get to the bottom of this before then

**Comment by Brotuulaan** [comment] 2022-08-01 21:22
That's unknown for my part. I only recently began using Companion, and 2.2.3 is where I entered. It does still happen when I turn off the other module I have set up.

**Comment by Brotuulaan** [comment] 2022-08-01 22:09
Is there a way for me to tell what version of websocket is currently installed? I don't see anything in the websocket GUI under the tools menu, and the websocket file doesn't include a version number in its name.

**Comment by Brotuulaan** [comment] 2022-08-01 22:12
It was installed quite a while ago (the file is dated "created 01/27/21" and "modified 05/26/20" (which always mystifies me, but it must be the file's "modification" by the author and its subsequent "creation" by the installer or something), so maybe updating it could fix the problem? Unless you can confirm the current version still has a hand in the issue at hand.

**Comment by Brotuulaan** [comment] 2022-08-01 22:13
Wait, are you Palakis over on the OBS forum?

**Comment by bryce-seifert** [comment] 2022-08-01 22:42
@Brotuulaan Can you try downloading the version named 4.9.1-compat at [this link](https://github.com/obsproject/obs-websocket/releases/tag/5.0.0). We'll very soon be moving to 5.0, but for now if you can give that I try I'm hoping it will resolve.

And I am not Palakis, but they are one of the devs of obs-websocket, which this module uses

**Comment by Brotuulaan** [comment] 2022-08-04 15:49
Oh, I see. I took your meaning to be that you were rewriting the websocket itself, but you meant that you were rewriting the module to work with the 5.0 websocket.

I'll install that version and will post the results.

**Comment by myntath** [comment] 2022-08-06 07:47
I'm not sure when this issue first appeared but I do not that it hasn't always existed.

I have installed the 4.9.1 company and that has solved the issue for me. Thanks.

**Comment by Brotuulaan** [comment] 2022-08-08 17:45
I don't know what version of OBS websocket we were on before, but I installed 4.9.1 and that seems to have fixed the problem. I was about to install the compat but held off in case 4.9.1 was enough, and it seems to be. I'll post back if later restarts and such bring the issue back, but this topic should be good to close now.

**Comment by bryce-seifert** [comment] 2022-08-15 11:50
Glad to hear updating the version fixed it.

I also verified this is working as expected in the latest release, which is now in the [beta builds of Companion](https://bitfocus.io/companion/download/builds/), for obs-websocket 5.0.0

**Closed by bryce-seifert** 2022-08-15 11:50 UTC
