### ISSUE TITLE
Where to find Hotkey ID?

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion-module-obs-studio#33] opened 2020-11-05 15:23 UTC
Call me stupid but I just can't find the Hotkey ID's for the latest addition to the OBS module "added trigger hotkey action"

Anyone can help?

**Comment by bryce-seifert** [comment] 2020-11-15 21:30
It looks like it's stored in the Profile files https://github.com/bitfocus/companion-module-obs-studio/pull/31

I haven't been able to make it work, though.

**Comment by wwboynton** [comment] 2020-11-24 23:55
@featherbear notes in #31 that the hotkey IDs can be found in the `basic.ini` file of your OBS Broadcaster settings.

It seems like while OBS default hotkeys on Windows are indeed stored in `%appdata%\Roaming\obs-studio\basic\profiles\Untitled\basic.ini` (start stream, stop stream, studio mode, etc.), hotkeys added by other plugins, and hotkeys specific to scenes and their elements aren't stored in that file. Adding an actual key combination to the entry in OBS does cause it to write to that `basic.ini` file, but it won't add any hotkeys that aren't at that root level.

Instead, I find them scattered throughout `%appdata%\Roaming\obs-studio\basic\scenes\My_Scenes.json` (your file will be named after your scene collection, so if your scene collection in OBS is called "Derpus" you'd look for `Derpus.json`).

The labels in that JSON file don't seem to constitute real hotkey IDs as far as OBS-Websocket is concerned. I'm not sure if OBS-Websocket expects some kind of a prefix to help it understand the parent(s) of the hotkey, or what. I don't understand at this point if the issue is upstream or if #31 just hasn't accurately documented how to get non-root-level hotkeys, but looking at OBS-Websocket, I don't even see a method for pulling a full list of all of the hotkeys and their unique identifiers.

**Comment by featherbear** [comment] 2020-11-25 04:27
@DachsbauTV @bryce-seifert 

# Getting It To Work

The hotkey trigger functionality requires functionality (https://github.com/Palakis/obs-websocket/pull/595 - 1st October) that does not exist in the [4.8.0](https://github.com/Palakis/obs-websocket/releases/tag/4.8.0) release (27th May). So in order to get this feature to work you will need to either compile a newer copy of obs-websocket yourself with https://github.com/Palakis/obs-websocket/pull/595 merged, or you could download it from their CI artifacts

<u>This only works for unique hotkey IDs.</u>

## ~Scene Specific Triggering~

As @wwboynton (thanks for tagging me else I wouldn't have seen it) mentioned, scene specific hotkeys are stored inside the respective `.json` file for the scene.

As an example, here is the related hotkey data to switch to a scene when I press `Shift + A`

```json
"OBSBasic.SelectScene": [
    {
        "key": "OBS_KEY_A",
        "shift": true
    }
]
```

`OBSBasic.SelectScene` is **not** unique, as multiple scene hotkeys share that identifier.

In order to trigger these ones, we will have to send the sequence of key strokes, and use the `TriggerHotkeyBySequence` call.  
**This will require another feature addition to `companion-module-obs-studio` - which I did not do**

> _Note however, this Companion module already allows you to do some scene-specific actions with the "Set Source Mute" and "Toggle scene visibility item"_

**Comment by rbyerly17** [comment] 2021-01-19 16:31
Where would I find their "CI artifacts"? Having hotkey functionality would be really helpful to me but compiling a new copy seems a little over my head. Thanks for any help!

**Comment by featherbear** [comment] 2021-01-19 23:20
> Where would I find their "CI artifacts"? Having hotkey functionality would be really helpful to me but compiling a new copy seems a little over my head. Thanks for any help!

Here's the link to their latest builds - https://dev.azure.com/Palakis/obs-websocket/_build/results?buildId=1620&view=artifacts&pathAsName=false&type=publishedArtifacts

Built against https://github.com/Palakis/obs-websocket/commit/bc3b09dce4bf25eb99007dabff078deb2f5b027d

**Comment by featherbear** [comment] 2021-01-19 23:22
(There's a drop down menu you need to access by hovering over the respective OS binary and then clicking on the dots on the righthand side)

________________________________

**Comment by rbyerly17** [comment] 2021-01-20 13:56
Thank you so much for this!

**Comment by DachsbauTV** [comment] 2021-01-28 16:50
So I've downloaded the latest build of websocket and the latest build of Companion, however, I still can't get it to work.

When using "Trigger hotkey by ID" the data field doesn't save anything that is entered into it.

My test button is supposed to trigger "SlideShow.NextSlide"

**Comment by rbyerly17** [comment] 2021-01-28 18:52
@DachsbauTV did you down load the latest version from featherbear's link? The 4.8.0 version on the regular Websocket Github doesn't have the functionality. Also it took me a while to understand what exactly in the profile is the 'Hotkey ID'. For start stream the correct ID is OBSBasic.StartStreaming .

**Comment by DachsbauTV** [comment] 2021-01-28 21:22
Yes sorry i was unclear there: i am using build 1620 websockets from the CI artifacts and companion build 2817

also i already figured out that if you use a shared identifier it will trigger the first source item of all the scenes that would fit the description. So it still can be used for some cases.

to make this extension really work well i think it needs an additional field in which you can select which source the hotkey belongs to.

Also so far i couldn't get it to work with plugin hotkeys (motion in my case)

**Closed** 2021-03-19 00:15 UTC
