### ISSUE TITLE
When using streamdeck to launch OBS, scenes do not load

### ISSUE THREAD

**Issue by ace2go** [bitfocus/companion-module-obs-studio#169] opened 2022-09-13 20:44 UTC
As the title states, if you load OBS Studio with the streamdeck, you cannot control the scenes.  If you execute the same shortcut that you linked the streamdeck to to launch OBS, then you are able to switch between scenes.

**Comment by bryce-seifert** [comment] 2022-09-14 02:48
Hello, I'm not quite sure exactly what the issue is here.

By " load OBS Studio with the streamdeck", do you mean you are using the Elgato "System: Open" action to open OBS?
If so, after that what actions are you using in Companion that aren't working?

Additionally, if you can provide version numbers of OBS and Companion, and any screenshots of the issue that would be helpful.

**Comment by bryce-seifert** [comment] 2022-09-18 11:52
@ace2go Are you able to provide any more info on this? I'm still unable to replicate

**Comment by bryce-seifert** [comment] 2022-09-27 00:24
Closing as I'm not able to replicate with provided information. Feel free to reopen if you have more info or steps to replicate

**Closed by bryce-seifert** 2022-09-27 00:24 UTC
