### ISSUE TITLE
Media File name not showing as it did before.

### ISSUE THREAD

**Issue by roleli** [bitfocus/companion-module-obs-studio#249] opened 2024-01-29 03:50 UTC
**Describe the bug**
Companion not displaying the files names of media sources being used in OBS

**To Reproduce**

In Companion: Set up a connection in Companion to an OBS Instance via WebSockets

In OBS: 
Create a scene and add media source  as shown below

Scene: test
Source: testmedia
File_name : testvideo.mp4

Move the test scene from preview to program  or select the scene to start playing

In Companion: 
Check in values returned in these variables for the OBS instance.
`$(obsp:current_media_name) ` works - returns testmedia 
`$(obsp:media_file_name_testmedia)` does not work - returns nothing. Should return testvideo.mp4

In the past we could use this to get the file name of the current media file playing
`$(obsp:media_file_name_$(obsp:current_media_name))` . In this e.g. testvideo.mp4

Note if the a VLC Video source  type is used instead of a media source within OBS it works as expected. (if the VLC source has more than 1 file it only shows the name of the  first file)

**Version Information:**

- Operating System: Window 10
- OBS Version: OBS 30.0.0
- Companion Versions: 3.2.0 and 3.1.2

**Comment by bryce-seifert** [comment] 2024-02-03 23:54
It looks like something might have changed slightly in the data coming in via websocket, and it broke this. I'm not sure what version of OBS the change happened, but I was able to recreate the issue.


I have fixed this, and the fix will be in the next version of the module.

> (if the VLC source has more than 1 file it only shows the name of the first file)
This is currently by design, as with the current API we have no way to know what the currently playing VLC playlist file is. And I figured that putting all the file names on a small button wouldn't be useful. But if you have more feedback about that given the limitations, let me know!

**Closed by bryce-seifert** 2024-02-03 23:54 UTC
Labels: Bug
