### ISSUE TITLE
Transition locks up if you switch between Cut/Fade

### ISSUE THREAD

**Issue by JustinTechGuyAtWork** [bitfocus/companion-module-obs-studio#205] opened 2023-03-22 18:42 UTC
**Describe the bug**
When I use a Fade transition it will only fade to one scene and then do two things. One, when the transition from preview to program finishes, what was supposed to become preview after the swap will layer itself back over the program scene. Two, the button to transition will lock up entirely where it won't preview another scene. I noticed the transition windows in OBS gray out as well.
I have my transition between scenes to be cuts normally and the fade button for some slates I have. If I double click to program a third scene within OBS it seems to reset the transitions. I think its the system swapping from one type to another that bugs it out.

**To Reproduce**

1. Set two scenes in OBS Studio
2. Set the primary transition to Cut
3. Then use the fade button back and forth between the two scenes
(Im using the Set Program/Preview buttons as well but I don't believe those are necessarily tied to the issue)

**Version Information:**

- Operating System: Windows 11 22H2
- OBS Version: 29.0.2
- Companion Version: 2.4.2

**Comment by bryce-seifert** [comment] 2023-03-23 02:54
I was able to recreate this. It seems like the issue is the Duration defaulting to "0". If you set the Duration to a specific time, like 500, it should prevent the lockup. So that is the temporary workaround.

I'm working on handling this better in v3, with a checkbox for custom duration.

**Comment by JustinTechGuyAtWork** [comment] 2023-03-23 03:03
Interesting. I was having the problem with it set to 1000ms but also noticed it with 0 as well.

**Comment by bryce-seifert** [comment] 2023-03-23 03:37
I’ll do some more testing on it with longer durations. In you example, are you hitting the fade button again before the transition completes?

**Comment by JustinTechGuyAtWork** [comment] 2023-03-23 04:52
No, only after it completes the first time

**Comment by bryce-seifert** [comment] 2023-03-24 02:30
I suspect that this has to do with how the commands are being send in 2.4, vs 3.0 where we use a batch command to send all the commands at once. So hopefully this fix will be good. Still working on getting the proper upgrade steps working before it hits the beta.

**Comment by bryce-seifert** [comment] 2023-04-06 02:45
Fixed with
https://github.com/bitfocus/companion-module-obs-studio/commit/1cd611b0272f898d27f57d09025ef51b3cab6573
https://github.com/bitfocus/companion-module-obs-studio/commit/bad4bc8eafa281dd42ec0c152b4abcebbf0c5aa3

**Closed by bryce-seifert** 2023-04-06 02:45 UTC
Labels: Bug
