### ISSUE TITLE
Behaviour of specified transition using 'Transition preview to program' 

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion-module-obs-studio#89] opened 2021-04-15 02:44 UTC
When specifying the transition and/or a duration to use within the 'Transition preview to program', it overwrites the 'default' transition within OBS. So that next time a 'default' transition is called it uses the newly changed transition.

Ideally I would like to see that a 'default' transition is stored (can be changed using set transition), and a specific transition could be used without changing the default.

**Comment by bryce-seifert** [comment] 2021-04-15 02:54
So basically after using that action, the expected behavior is if the action transition != previous transition used, it returns to the previous transition? I can take a look at this.

**Comment by jmcc94** [comment] 2021-04-15 05:44
Exactly - I was looking for a result similar to using 'Quick Transitions' in OBS front end - where a transition can happen without changing the 'default' transition.

It would be fantastic if this module could access that behavior as well - preset transitions with specific settings could be stored, and recalled as appropriate.

Thanks for all your work on this!

**Comment by bryce-seifert** [comment] 2021-04-17 15:54
So I have this half-working using the Execute Batch command to send both the TransitiontoProgram and then SetTransition. After some debugging to try and figure it out, I *think* the issue is that OBS gets confused if the SetTransition action happens while a transition is active. 

So, this one may have to wait on the [Sleep parameter](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sleep) to be released in obs-websocket so that we can wait for the transition to finish before attempting to change it

**Comment by jmcc94** [comment] 2021-04-17 20:16
Thanks for your work on this! It probably doesn't help that TransitionToProgram changes the active transition if specified, not just using the specified for only that time.

My use case is I have 'AUTO' button that uses the default transition (which I can change on another page) as well as a specific 'CUT' transition button. Whenever I use the cut button, it changes the default transition... very frustrating.

I've also raised an issue in obs-websocket asking for 'Quick Transitions' to be exposed.

**Closed** 2021-06-21 14:16 UTC
